# Form implementation generated from reading ui file 'finaiui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from inoper import InUi_Dialog 
from outoper import OutUi_Dialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 705)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inp_btn = QtWidgets.QPushButton(parent=self.frame)
        self.inp_btn.setEnabled(True)
        self.inp_btn.setObjectName("inp_btn")
        self.verticalLayout_2.addWidget(self.inp_btn)
        self.outp_btn = QtWidgets.QPushButton(parent=self.frame)
        self.outp_btn.setObjectName("outp_btn")
        self.verticalLayout_2.addWidget(self.outp_btn)
        self.optimize_btn = QtWidgets.QPushButton(parent=self.frame)
        self.optimize_btn.setEnabled(True)
        self.optimize_btn.setObjectName("optimize_btn")
        self.verticalLayout_2.addWidget(self.optimize_btn)
        self.upd_btn = QtWidgets.QPushButton(parent=self.frame)
        self.upd_btn.setObjectName("upd_btn")
        self.verticalLayout_2.addWidget(self.upd_btn)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.ai_page = QtWidgets.QWidget()
        self.ai_page.setObjectName("ai_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ai_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.ai_page)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 2)
        self.mbtn_aip = QtWidgets.QPushButton(parent=self.ai_page)
        self.mbtn_aip.setObjectName("mbtn_aip")
        self.gridLayout_4.addWidget(self.mbtn_aip, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.ai_page)
        self.in_page = QtWidgets.QWidget()
        self.in_page.setObjectName("in_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.in_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_2 = QtWidgets.QWidget(parent=self.in_page)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6.addWidget(self.widget_2, 5, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_26 = QtWidgets.QLabel(parent=self.in_page)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_13.addWidget(self.label_26)
        self.othincomeline = QtWidgets.QLineEdit(parent=self.in_page)
        self.othincomeline.setObjectName("othincomeline")
        self.horizontalLayout_13.addWidget(self.othincomeline)
        self.oi_autobtn = QtWidgets.QCheckBox(parent=self.in_page)
        self.oi_autobtn.setObjectName("oi_autobtn")
        self.horizontalLayout_13.addWidget(self.oi_autobtn)
        self.label_27 = QtWidgets.QLabel(parent=self.in_page)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_13.addWidget(self.label_27)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 4, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_22 = QtWidgets.QLabel(parent=self.in_page)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.secincomeline = QtWidgets.QLineEdit(parent=self.in_page)
        self.secincomeline.setObjectName("secincomeline")
        self.horizontalLayout_11.addWidget(self.secincomeline)
        self.si_autobtn = QtWidgets.QCheckBox(parent=self.in_page)
        self.si_autobtn.setObjectName("si_autobtn")
        self.horizontalLayout_11.addWidget(self.si_autobtn)
        self.label_23 = QtWidgets.QLabel(parent=self.in_page)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_21 = QtWidgets.QLabel(parent=self.in_page)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.mainincomeline = QtWidgets.QLineEdit(parent=self.in_page)
        self.mainincomeline.setObjectName("mainincomeline")
        self.horizontalLayout.addWidget(self.mainincomeline)
        self.mi_autobtn = QtWidgets.QCheckBox(parent=self.in_page)
        self.mi_autobtn.setObjectName("mi_autobtn")
        self.horizontalLayout.addWidget(self.mi_autobtn)
        self.label_20 = QtWidgets.QLabel(parent=self.in_page)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.gridLayout_6.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.totalin = QtWidgets.QLabel(parent=self.in_page)
        self.totalin.setStyleSheet("border: 2px solid darkgray; \n"
"    border-radius: 10px;        \n"
"    padding: 15px;             \n"
"    background-color: solid darkgray;  \n"
"    color: white;              \n"
"    font-size: 18px;         \n"
"    font-weight: bold;\n"
"    min-width: 200px;    \n"
"    min-height: 100px;         \n"
"    text-align: center;")
        self.totalin.setObjectName("totalin")
        self.gridLayout_6.addWidget(self.totalin, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mbtn_inp = QtWidgets.QPushButton(parent=self.in_page)
        self.mbtn_inp.setObjectName("mbtn_inp")
        self.verticalLayout.addWidget(self.mbtn_inp)
        self.intrans = QtWidgets.QPushButton(parent=self.in_page)
        self.intrans.setObjectName("intrans")
        self.verticalLayout.addWidget(self.intrans)
        self.saveinch = QtWidgets.QPushButton(parent=self.in_page)
        self.saveinch.setObjectName("saveinch")
        self.verticalLayout.addWidget(self.saveinch)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.in_page)
        self.out_page = QtWidgets.QWidget()
        self.out_page.setObjectName("out_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.out_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.totalout = QtWidgets.QLabel(parent=self.out_page)
        self.totalout.setStyleSheet("border: 2px solid darkgray; \n"
"    border-radius: 10px;        \n"
"    padding: 15px;             \n"
"    background-color: solid darkgray;  \n"
"    color: white;              \n"
"    font-size: 18px;         \n"
"    font-weight: bold;\n"
"    min-width: 200px;    \n"
"    min-height: 100px;         \n"
"    text-align: center;")
        self.totalout.setObjectName("totalout")
        self.horizontalLayout_9.addWidget(self.totalout)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.outtrans = QtWidgets.QPushButton(parent=self.out_page)
        self.outtrans.setObjectName("outtrans")
        self.gridLayout.addWidget(self.outtrans, 1, 0, 1, 1)
        self.mbtn_outp = QtWidgets.QPushButton(parent=self.out_page)
        self.mbtn_outp.setObjectName("mbtn_outp")
        self.gridLayout.addWidget(self.mbtn_outp, 0, 0, 1, 1)
        self.saveoutch = QtWidgets.QPushButton(parent=self.out_page)
        self.saveoutch.setObjectName("saveoutch")
        self.gridLayout.addWidget(self.saveoutch, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_46 = QtWidgets.QLabel(parent=self.out_page)
        self.label_46.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_20.addWidget(self.label_46)
        self.othout_spent = QtWidgets.QLabel(parent=self.out_page)
        self.othout_spent.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.othout_spent.setObjectName("othout_spent")
        self.horizontalLayout_20.addWidget(self.othout_spent)
        self.label_48 = QtWidgets.QLabel(parent=self.out_page)
        self.label_48.setStyleSheet("padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_20.addWidget(self.label_48)
        self.othout_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.othout_line.setObjectName("othout_line")
        self.horizontalLayout_20.addWidget(self.othout_line)
        self.label_53 = QtWidgets.QLabel(parent=self.out_page)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_20.addWidget(self.label_53)
        self.othout_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.othout_prio.setObjectName("othout_prio")
        self.othout_prio.addItem("")
        self.othout_prio.addItem("")
        self.othout_prio.addItem("")
        self.othout_prio.addItem("")
        self.othout_prio.setItemText(3, "")
        self.horizontalLayout_20.addWidget(self.othout_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 9, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_43 = QtWidgets.QLabel(parent=self.out_page)
        self.label_43.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_19.addWidget(self.label_43)
        self.enj_spent = QtWidgets.QLabel(parent=self.out_page)
        self.enj_spent.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.enj_spent.setObjectName("enj_spent")
        self.horizontalLayout_19.addWidget(self.enj_spent)
        self.label_45 = QtWidgets.QLabel(parent=self.out_page)
        self.label_45.setStyleSheet("padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_19.addWidget(self.label_45)
        self.enj_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.enj_line.setObjectName("enj_line")
        self.horizontalLayout_19.addWidget(self.enj_line)
        self.label_52 = QtWidgets.QLabel(parent=self.out_page)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_19.addWidget(self.label_52)
        self.enj_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.enj_prio.setObjectName("enj_prio")
        self.enj_prio.addItem("")
        self.enj_prio.addItem("")
        self.enj_prio.addItem("")
        self.enj_prio.addItem("")
        self.enj_prio.setItemText(3, "")
        self.horizontalLayout_19.addWidget(self.enj_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 8, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.out_page)
        self.label_8.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.travs_spent = QtWidgets.QLabel(parent=self.out_page)
        self.travs_spent.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.travs_spent.setObjectName("travs_spent")
        self.horizontalLayout_6.addWidget(self.travs_spent)
        self.label_19 = QtWidgets.QLabel(parent=self.out_page)
        self.label_19.setStyleSheet("padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.travs_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.travs_line.setObjectName("travs_line")
        self.horizontalLayout_6.addWidget(self.travs_line)
        self.label_51 = QtWidgets.QLabel(parent=self.out_page)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_6.addWidget(self.label_51)
        self.travs_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.travs_prio.setObjectName("travs_prio")
        self.travs_prio.addItem("")
        self.travs_prio.addItem("")
        self.travs_prio.addItem("")
        self.travs_prio.addItem("")
        self.travs_prio.setItemText(3, "")
        self.horizontalLayout_6.addWidget(self.travs_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 7, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_40 = QtWidgets.QLabel(parent=self.out_page)
        self.label_40.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_18.addWidget(self.label_40)
        self.subs_spent = QtWidgets.QLabel(parent=self.out_page)
        self.subs_spent.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.subs_spent.setObjectName("subs_spent")
        self.horizontalLayout_18.addWidget(self.subs_spent)
        self.label_42 = QtWidgets.QLabel(parent=self.out_page)
        self.label_42.setStyleSheet("padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_18.addWidget(self.label_42)
        self.subs_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.subs_line.setObjectName("subs_line")
        self.horizontalLayout_18.addWidget(self.subs_line)
        self.label_50 = QtWidgets.QLabel(parent=self.out_page)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_18.addWidget(self.label_50)
        self.subs_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.subs_prio.setObjectName("subs_prio")
        self.subs_prio.addItem("")
        self.subs_prio.addItem("")
        self.subs_prio.addItem("")
        self.subs_prio.addItem("")
        self.subs_prio.setItemText(3, "")
        self.horizontalLayout_18.addWidget(self.subs_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 6, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_34 = QtWidgets.QLabel(parent=self.out_page)
        self.label_34.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_16.addWidget(self.label_34)
        self.shop_spent = QtWidgets.QLabel(parent=self.out_page)
        self.shop_spent.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.shop_spent.setObjectName("shop_spent")
        self.horizontalLayout_16.addWidget(self.shop_spent)
        self.label_36 = QtWidgets.QLabel(parent=self.out_page)
        self.label_36.setStyleSheet("padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_16.addWidget(self.label_36)
        self.shop_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.shop_line.setObjectName("shop_line")
        self.horizontalLayout_16.addWidget(self.shop_line)
        self.label_49 = QtWidgets.QLabel(parent=self.out_page)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_16.addWidget(self.label_49)
        self.shop_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.shop_prio.setObjectName("shop_prio")
        self.shop_prio.addItem("")
        self.shop_prio.addItem("")
        self.shop_prio.addItem("")
        self.shop_prio.addItem("")
        self.shop_prio.setItemText(3, "")
        self.horizontalLayout_16.addWidget(self.shop_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_16, 5, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_37 = QtWidgets.QLabel(parent=self.out_page)
        self.label_37.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_17.addWidget(self.label_37)
        self.health_spent_2 = QtWidgets.QLabel(parent=self.out_page)
        self.health_spent_2.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.health_spent_2.setObjectName("health_spent_2")
        self.horizontalLayout_17.addWidget(self.health_spent_2)
        self.label_39 = QtWidgets.QLabel(parent=self.out_page)
        self.label_39.setStyleSheet("padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_17.addWidget(self.label_39)
        self.food_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.food_line.setObjectName("food_line")
        self.horizontalLayout_17.addWidget(self.food_line)
        self.label_25 = QtWidgets.QLabel(parent=self.out_page)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_17.addWidget(self.label_25)
        self.food_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.food_prio.setObjectName("food_prio")
        self.food_prio.addItem("")
        self.food_prio.addItem("")
        self.food_prio.addItem("")
        self.food_prio.addItem("")
        self.food_prio.setItemText(3, "")
        self.horizontalLayout_17.addWidget(self.food_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_17, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(parent=self.out_page)
        self.label_14.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.health_spent = QtWidgets.QLabel(parent=self.out_page)
        self.health_spent.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.health_spent.setObjectName("health_spent")
        self.horizontalLayout_5.addWidget(self.health_spent)
        self.label_16 = QtWidgets.QLabel(parent=self.out_page)
        self.label_16.setStyleSheet("padding: 5px;\n"
"background-color: solid darkgray;\n"
" color: white; ")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.health_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.health_line.setObjectName("health_line")
        self.horizontalLayout_5.addWidget(self.health_line)
        self.label_24 = QtWidgets.QLabel(parent=self.out_page)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        self.health_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.health_prio.setObjectName("health_prio")
        self.health_prio.addItem("")
        self.health_prio.addItem("")
        self.health_prio.addItem("")
        self.health_prio.addItem("")
        self.health_prio.setItemText(3, "")
        self.horizontalLayout_5.addWidget(self.health_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(parent=self.out_page)
        self.label_11.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.transp_spent = QtWidgets.QLabel(parent=self.out_page)
        self.transp_spent.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.transp_spent.setObjectName("transp_spent")
        self.horizontalLayout_4.addWidget(self.transp_spent)
        self.label_13 = QtWidgets.QLabel(parent=self.out_page)
        self.label_13.setStyleSheet("padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.transp_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.transp_line.setObjectName("transp_line")
        self.horizontalLayout_4.addWidget(self.transp_line)
        self.label_17 = QtWidgets.QLabel(parent=self.out_page)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.transp_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.transp_prio.setObjectName("transp_prio")
        self.transp_prio.addItem("")
        self.transp_prio.addItem("")
        self.transp_prio.addItem("")
        self.horizontalLayout_4.addWidget(self.transp_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.out_page)
        self.label_5.setStyleSheet("border: 2px solid darkgray;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.bills_spent = QtWidgets.QLabel(parent=self.out_page)
        self.bills_spent.setStyleSheet("border: 1px solid darkgray;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.bills_spent.setObjectName("bills_spent")
        self.horizontalLayout_2.addWidget(self.bills_spent)
        self.label_7 = QtWidgets.QLabel(parent=self.out_page)
        self.label_7.setStyleSheet("\n"
"    padding: 5px;\n"
"    background-color: solid darkgray;\n"
"    color: white; ")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.bills_line = QtWidgets.QLineEdit(parent=self.out_page)
        self.bills_line.setObjectName("bills_line")
        self.horizontalLayout_2.addWidget(self.bills_line)
        self.label_10 = QtWidgets.QLabel(parent=self.out_page)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(parent=self.out_page)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.bills_prio = QtWidgets.QComboBox(parent=self.out_page)
        self.bills_prio.setObjectName("bills_prio")
        self.bills_prio.addItem("")
        self.bills_prio.addItem("")
        self.bills_prio.addItem("")
        self.bills_prio.addItem("")
        self.bills_prio.setItemText(3, "")
        self.horizontalLayout_2.addWidget(self.bills_prio)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.out_page)
        self.Main_page = QtWidgets.QWidget()
        self.Main_page.setObjectName("Main_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Main_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(parent=self.Main_page)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Main_page)
        self.gridLayout_5.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.inp_btn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.in_page))
        self.outp_btn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.out_page))
        self.optimize_btn.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.ai_page))
        self.mbtn_aip.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Main_page))
        self.mbtn_inp.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Main_page))
        self.mbtn_outp.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.Main_page))
        self.stackedWidget.setCurrentWidget(self.Main_page)
        #self.intrans.clicked.connect(self.open_income_dialog)
        #self.outtrans.clicked.connect(self.open_expense_dialog)


        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #def open_income_dialog(self):
        #InUi_Dialog(self)

    #def open_expense_dialog(self):
        #OutUi_Dialog(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inp_btn.setText(_translate("MainWindow", "Доходы"))
        self.outp_btn.setText(_translate("MainWindow", "Расходы"))
        self.optimize_btn.setText(_translate("MainWindow", "Оптимизация"))
        self.upd_btn.setText(_translate("MainWindow", "Обновить"))
        self.label_2.setText(_translate("MainWindow", "A.I."))
        self.mbtn_aip.setText(_translate("MainWindow", "Главная стр."))
        self.label_26.setText(_translate("MainWindow", "Другое"))
        self.oi_autobtn.setText(_translate("MainWindow", "Авто считывание"))
        self.label_22.setText(_translate("MainWindow", "Пассивный Доход и Соц.выплаты"))
        self.si_autobtn.setText(_translate("MainWindow", "Авто считывание"))
        self.label_21.setText(_translate("MainWindow", "Основной Доход"))
        self.mi_autobtn.setText(_translate("MainWindow", "Авто. считывание"))
        self.totalin.setText(_translate("MainWindow", "Суммарный Доход(мес.):"))
        self.mbtn_inp.setText(_translate("MainWindow", "Главная стр."))
        self.intrans.setText(_translate("MainWindow", "Транзакция"))
        self.saveinch.setText(_translate("MainWindow", "Сохранить Изм."))
        self.totalout.setText(_translate("MainWindow", "Суммарный Расход(мес.):"))
        self.outtrans.setText(_translate("MainWindow", "Транзакция"))
        self.mbtn_outp.setText(_translate("MainWindow", "Главная стр."))
        self.saveoutch.setText(_translate("MainWindow", "Сохранить Изм."))
        self.label_46.setText(_translate("MainWindow", "Другое"))
        self.othout_spent.setText(_translate("MainWindow", "Потрачено"))
        self.label_48.setText(_translate("MainWindow", "Бюджет"))
        self.label_53.setText(_translate("MainWindow", "Приоритет"))
        self.othout_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.othout_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.othout_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label_43.setText(_translate("MainWindow", "Развлечения"))
        self.enj_spent.setText(_translate("MainWindow", "Потрачено"))
        self.label_45.setText(_translate("MainWindow", "Бюджет"))
        self.label_52.setText(_translate("MainWindow", "Приоритет"))
        self.enj_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.enj_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.enj_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label_8.setText(_translate("MainWindow", "Путешествия"))
        self.travs_spent.setText(_translate("MainWindow", "Потрачено"))
        self.label_19.setText(_translate("MainWindow", "Бюджет:"))
        self.label_51.setText(_translate("MainWindow", "Приоритет"))
        self.travs_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.travs_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.travs_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label_40.setText(_translate("MainWindow", "Подписки"))
        self.subs_spent.setText(_translate("MainWindow", "Потрачено"))
        self.label_42.setText(_translate("MainWindow", "Бюджет"))
        self.label_50.setText(_translate("MainWindow", "Приоритет"))
        self.subs_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.subs_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.subs_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label_34.setText(_translate("MainWindow", "Покупки"))
        self.shop_spent.setText(_translate("MainWindow", "Потрачено"))
        self.label_36.setText(_translate("MainWindow", "Бюджет"))
        self.label_49.setText(_translate("MainWindow", "Приоритет"))
        self.shop_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.shop_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.shop_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label_37.setText(_translate("MainWindow", "Еда"))
        self.health_spent_2.setText(_translate("MainWindow", "Потрачено"))
        self.label_39.setText(_translate("MainWindow", "Бюджет"))
        self.label_25.setText(_translate("MainWindow", "Приоритет"))
        self.food_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.food_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.food_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label_14.setText(_translate("MainWindow", "Здоровье и фитнес"))
        self.health_spent.setText(_translate("MainWindow", "Потрачено"))
        self.label_16.setText(_translate("MainWindow", "Бюджет:"))
        self.label_24.setText(_translate("MainWindow", "Приоритет"))
        self.health_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.health_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.health_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label_11.setText(_translate("MainWindow", "Транспорт"))
        self.transp_spent.setText(_translate("MainWindow", "Потрачено"))
        self.label_13.setText(_translate("MainWindow", "Бюджет:"))
        self.label_17.setText(_translate("MainWindow", "Приоритет"))
        self.transp_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.transp_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.transp_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label_5.setText(_translate("MainWindow", "Ком.платежи и сборы"))
        self.bills_spent.setText(_translate("MainWindow", "Потрачено:"))
        self.label_7.setText(_translate("MainWindow", "Бюджет:"))
        self.label_10.setText(_translate("MainWindow", "Приоритет"))
        self.bills_prio.setItemText(0, _translate("MainWindow", "Низкий"))
        self.bills_prio.setItemText(1, _translate("MainWindow", "Средний"))
        self.bills_prio.setItemText(2, _translate("MainWindow", "Высокий"))
        self.label.setText(_translate("MainWindow", "График"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

