# Form implementation generated from reading ui file 'goal_fix.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class goalfixui_dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.goalsetbtn = QtWidgets.QPushButton(parent=Dialog)
        self.goalsetbtn.setObjectName("pushButton")
        self.gridLayout.addWidget(self.goalsetbtn, 3, 1, 1, 1)
        self.goalsum = QtWidgets.QLineEdit(parent=Dialog)
        self.goalsum.setObjectName("goalsum")
        self.gridLayout.addWidget(self.goalsum, 2, 1, 1, 1)
        self.goaldate = QtWidgets.QDateEdit(parent=Dialog)
        self.goaldate.setObjectName("goaldate")
        self.gridLayout.addWidget(self.goaldate, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.goalname = QtWidgets.QLineEdit(parent=Dialog)
        self.goalname.setObjectName("goalname")
        self.gridLayout.addWidget(self.goalname, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Сумма "))
        self.goalsetbtn.setText(_translate("Dialog", "Задать цель"))
        self.label.setText(_translate("Dialog", "Срок"))
        self.label_3.setText(_translate("Dialog", "Название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = goalfixui_dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
