# Form implementation generated from reading ui file 'out_oper_del.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Out_Ui_Del_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 40, 321, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("font: 16pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.outdelsum = QtWidgets.QLineEdit(parent=self.frame)
        self.outdelsum.setObjectName("outdelsum")
        self.verticalLayout_2.addWidget(self.outdelsum)
        self.outdelconfirm = QtWidgets.QPushButton(parent=self.frame)
        self.outdelconfirm.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.outdelconfirm)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Удалить транзакцию(расход)"))
        self.label_2.setText(_translate("Dialog", "ID транзакции:"))
        self.outdelconfirm.setText(_translate("Dialog", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Out_Ui_Del_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
